### ISSUE TITLE
env.yml

### ISSUE THREAD

**Issue by pokaxpoka** [google-research/dads#6]
Hi, Archit, thanks for sharing your code.

I have the following issue: The package "tf-nightly==2.2.0.dev20200229" in env.yml could not be installed. I installed with the latest version "2.5.0.dev20200629" but there is some version issue. `from tensorflow.python.autograph.core import naming ImportError: cannot import name 'naming'`.

Thanks

**Comment by architsharma97** [comment]
Hi,
I have updated env.yml so that tensorflow dependencies can be installed properly. However, mujoco-py seems to be giving me some trouble, and I am not sure if the conda environment works. If you encounter issues with mujoco-py, please follow this thread: https://github.com/openai/mujoco-py/issues/383

**Comment by pokaxpoka** [comment]
Thank you very much for quick response! It works!!
